/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Frame-Options: deny  
  X-XSS-Protection: 1; mode=block
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self';
  X-Content-Type-Options: nosniff
