[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "must-revalidate"
        Proxy-Authenticate = "Basic"
        X-Permitted-Cross-Domain-Policies = "none"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        X-Download-Options = "noopen"
        Expect-CT = "enforce, max-age=31536000 report-uri https://maxsspot.report-uri.com/r/d/ct/enforce"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "unsafe-none"
        
        Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'self' https:;
            script-src 'nonce-JJsam12MMsazks2312' 'strict-dynamic';
            style-src 'nonce-cmFkZHVkZXNvcmFkaWNhbA==' 'nonce-Mask31278Ausam92' 'strict-dynamic';
            object-src 'none';
            base-uri 'none';
            frame-src 'none';
            manifest-src 'none';
            connect-src https://www.googletagmanager.com/gtag/js?id=G-538KEJSXY6;
            upgrade-insecure-requests;
        '''
        
        Permissions-Policy = '''
            accelerometer=(none),
            ambient-light-sensor=(none),
            autoplay=(none),
            camera=(none),
            fullscreen=(none),
            geolocation=(none),
            gyroscope=(none),
            magnetometer=(none),
            microphone=(none),
            midi=(none),
            payment=(none),
            picture-in-picture=(none),
            speaker=(none),
            usb=(none),
            vibrate=(none),
            vr=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
