[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "max-age=604800, must-revalidate"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Access-Control-Allow-Origin = "www.maxwellblog.com"

        Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'none';
            script-src 'nonce-d2h5eW91ZGVjb2RldGhpcw==' 'report-sample';
            style-src 'nonce-cmFkZHVkZXNvcmFkaWNhbA==' 'nonce-c3VwZXJpZG9sZG9taXRhbg==' 'report-sample' https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            font-src https://fonts.gstatic.com https://cdnjs.cloudflare.com;
            form-action 'self' https://www.maxwellblog.com/submitted;
            img-src https:;
            base-uri 'none';
            connect-src https://www.googletagmanager.com/gtag/js?id=G-538KEJSXY6;
            upgrade-insecure-requests;
            report-uri https://maxsspot.report-uri.com/r/d/csp/enforce;
        '''
        
        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
