[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Access-Control-Allow-Origin = "www.maxwellblog.com"
        Vary = "Origin"
        Cache-Control = "must-revalidate"
        Proxy-Authenticate = "Basic"
        X-Permitted-Cross-Domain-Policies = "none"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        X-Download-Options = "noopen"
        Expect-CT = "max-age=31536000, enforce, https://maxsspot.report-uri.com/r/d/ct/enforce"
        
        Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'self';
            script-src 'nonce-d2h5eW91ZGVjb2RldGhpcw==' 'strict-dynamic';
            style-src 'nonce-cmFkZHVkZXNvcmFkaWNhbA==' 'nonce-c3VwZXJpZG9sZG9taXRhbg==' 'strict-dynamic' https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            object-src 'none';
            img-src https://www.dropbox.com/s/uam2lxsmux8pbvk/1249063%281%29.jpg?raw=1 https://www.dropbox.com/s/4z8sppoec485a4a/1249064%281%29.jpg?raw=1 https://www.dropbox.com/s/ec390h3f0huju6u/1249065%281%29.jpg?raw=1 https://www.dropbox.com/s/poeovl5wksl02kh/1249066%281%29.jpg?raw=1;
            base-uri 'none';
            frame-src 'none';
            font-src https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap;
            manifest-src 'none';
            connect-src https://www.googletagmanager.com/gtag/js?id=G-538KEJSXY6;
            upgrade-insecure-requests;
        '''
        
        Permissions-Policy = '''
            intrest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
