[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "no-cache"
        Proxy-Authenticate = "Basic"
        Pragma = "must-revalidate"
        X-Permitted-Cross-Domain-Policies = "none"
        Upgrade-Insecure-Requests = "1"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        X-Download-Options = "noopen"
        Expect-CT = "enforce, max-age=31536000 report-uri https://maxsspot.report-uri.com/r/d/ct/enforce"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "unsafe-none"
        Host = "www.maxwellblog.com"
        Location = "www.maxwellblog.com"
        Vary = "Upgrade-Insecure-Requests"
        Strict-Transport-Security = '''
            includeSubDomains
            max-age=31536000;
        '''
        Content-Security-Policy = '''
            default-src 'self' https:;
            script-src 'self';
            style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            object-src 'none';
            base-uri 'none';
            frame-src 'none';
            manifest-src 'none';
            upgrade-insecure-requests;
        '''
        Permissions-Policy = '''
            accelerometer=(none),
            ambient-light-sensor=(none),
            autoplay=(none),
            camera=(none),
            fullscreen=(none),
            geolocation=(none),
            gyroscope=(none),
            magnetometer=(none),
            microphone=(none),
            midi=(none),
            payment=(none),
            picture-in-picture=(none),
            speaker=(none),
            usb=(none),
            vibrate=(none),
            vr=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
