[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Cache-Control = "must-revalidate"
        Content-Language = "en-US"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        
        Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'self';
            script-src 'nonce-d2h5eW91ZGVjb2RldGhpcw==' 'report-sample';
            style-src 'nonce-cmFkZHVkZXNvcmFkaWNhbA==' 'nonce-c3VwZXJpZG9sZG9taXRhbg==' 'report-sample' https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            object-src 'none';
            child-src 'none';
            frame-src 'none';
            media-src 'none';
            navigate-to 'none';
            base-uri 'none';
            font-src https://fonts.gstatic.com https://cdnjs.cloudflare.com;
            worker-src 'none';
            frame-ancestors 'none';
            form-action 'self' https://www.maxwellblog.com/submitted;
            manifest-src 'none';
            img-src https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.onlinewebfonts.com%2Fsvg%2Fimg_56623.png&f=1&nofb=1 https://www.dropbox.com/s/zqmf47qxui6zwzo/pxl_20220215_115701495.jpg?raw=1;
            connect-src https://www.googletagmanager.com/gtag/js?id=G-538KEJSXY6;
            upgrade-insecure-requests;
            report-uri https://maxsspot.report-uri.com/r/d/csp/enforce;
        '''
        
        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
