[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Access-Control-Allow-Origin = "https://www.maxwellblog.com"
        Vary = "Origin"
        Cache-Control = "must-revalidate"
        Proxy-Authenticate = "Basic"
        X-Permitted-Cross-Domain-Policies = "none"
        Content-Language = "en-US"
        X-DNS-Prefetch-Control = "off"
        Keep-Alive = "100"
        Connection = "keep-alive"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        X-Download-Options = "noopen"
        Expect-CT = "enforce, max-age=31536000"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "unsafe-none"
        
        Strict-Transport-Security = '''
            max-age=31536000;
            includeSubDomains;
            preload
        '''
        
        Content-Security-Policy = '''
            default-src 'none';
            script-src 'nonce-d2h5eW91ZGVjb2RldGhpcw==' 'report-sample';
            style-src 'nonce-cmFkZHVkZXNvcmFkaWNhbA==' 'nonce-c3VwZXJpZG9sZG9taXRhbg==' 'report-sample' https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css;
            object-src 'none';
            child-src 'none';
            media-src 'none';
            navigate-to 'none';
            base-uri 'none';
            font-src https://fonts.gstatic.com https://cdnjs.cloudflare.com;
            img-src *.dropbox.com;
            worker-src 'none';
            frame-src 'none';
            frame-ancestors 'none';
            form-action 'none';
            manifest-src 'none';
            connect-src https://www.googletagmanager.com/gtag/js?id=G-538KEJSXY6;
            require-trusted-types-for 'script';
            upgrade-insecure-requests;
            report-uri https://maxsspot.report-uri.com/r/d/csp/enforce;
        '''
        
        Permissions-Policy = '''
            interest-cohort=(none)
        '''
 
        [[redirects]]
        from = "/*"
        to = "/pagenotfound.html"
        status = 404
